### PR TITLE
Hiding the iPhone Tab Bar with TTNavigator - Article

### PR DESCRIPTION
**Pull request by seqoy**
An article that show how to hide the iPhone Tab Bar when pushing some View Controller using TTNavigator.

### CODE REVIEW

**Comment by jverkoey** [comment]
I'm not sure what the difference is between doing this and just specifying hidesBottomBarWhenPushed in the view controller that's about to be pushed. TTWebController, for example, has this property so that when it is pushed onto a tab bar nav stack the bottom bar automatically disappears.

https://github.com/facebook/three20/blob/master/src/Three20UI/Sources/TTWebController.m#L54

**Comment by seqoy** [comment]
I don't see this property on normal View Controllers (e.g. Customs). If you use TTNavigator Mapped Controllers, you doesn't has access to the View Controller, since everything is working "under the hood". This trick works for me, because the delegate gives me access to the View Controller before he push to the stack.

**Comment by seqoy** [comment]
More concise example, i mapped some class:
        [map from:@"tt://login/(initWithUser:)" toSharedViewController:[GFLoginViewController class]];

I "call" this class like this:
    TTURLAction *action =  [TTURLAction actionWithURLPath: [NSString stringWithFormat:@"tt://login/%@", anUser.user]];

```
// Open with URL.
[navigator openURLAction:action];
```

I want that when the Login View Controller enter on screen the Tab Bar disappear. But i doesn't have acess to the View Controller Object Instance, since everything is made using the "Navigator Engine".

**Comment by jverkoey** [comment]
Ah, I see. So this is for adding this property to view controllers that you haven't created yourself (perhaps they're in a third-party library like Three20 even) and you want to add the hidesBottomBarWhenPushed property.

**Comment by jverkoey** [comment]
And you don't have access to the GFLoginViewController implementation, right?

**Comment by seqoy** [comment]
Generic i guess. Some that you're subclassing or that you created. But you doesn't initiate using normal "init" methods, but you let the all "Navigator Engine" works for you (like on the example above). But you need to have "access" to this instance before he enters on screen. Maybe the tutorial isn't clear enough.

**Comment by seqoy** [comment]
```
 @implementation GFLoginViewController
 ...

 -(void)navigator:(TTBaseNavigator *)navigator willOpenURL:(NSURL *)URL inViewController:(UIViewController *)controller {
        // This code hide the Tab Bar and automatically displays when the view is popped.
        controller.hidesBottomBarWhenPushed = YES; 
 }
 ...
 @end
```

**Comment by jverkoey** [comment]
This article definitely covers a useful topic, I just want to make sure that we present the simplest solution. If you have access to the implementation of a view controller, regardless of whether you're creating it through TTNavigator, you should still be able to implement an init chain and set the hidesBottomBarWhenPushed property.

That being said, if you don't have access to the implementation of a view controller, then this is probably the only way around it.

**Comment by seqoy** [comment]
I try to set the property directly on the "inits" methods and other "no elegant" manners too. But as you known, Obj-C sometimes doesn't let you do things the way you want. I'm sharing the solution because drive me a little crazy until reach this one.

**Comment by seqoy** [comment]
Yes, i double checked my code and you have reason. I'll update the tutorial with the things that we discuss here. Giving the example using the delegate to View Controllers that you doesn't have access to the implementation and setting the property on init methods if you do.

**Comment by seqoy** [comment]
Done. If think is much more clear now, take a look.

**Comment by jverkoey** [comment]
Thanks for adding the part about owning the controller. There's just a few other things to touch up on the article before we push it to Three20.info.

If you want to link to the API docs, Three20.info can intelligently do this for you if you wrap the Three20 class in back quotes, like this: `TTNavigator`. This way we don't have to hard-code any API links into the articles and the article looks much cleaner as a result.

When writing the article, it helps with diffing if you spread long lines out over multiple lines. The standard used so far is to break each line at the 100 character mark, wrapping at words.

I've also been trying to include a sample project with each article on Three20.info that shows the code in action. This will generally just make it a lot easier for people to try out the code and see it in context. Can you add a simple sample project to the Three20/Samples repo?

Thanks much for putting this together again seqoy.

**Comment by seqoy** [comment]
Ok, changes made. I will upload this project example later.

**Comment by jverkoey** [comment]
Merge branch &#39;seqoy-master&#39; into development

Closed by 7d8f84af5806bc3e3219890c14de1b1dddbeaf67.

**Comment by jverkoey** [comment]
Sorry this took so long seqoy, it'll go out in the next push to the site though!

**Pull request closed without merging**
